name: docker-image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container: maciejskorski/jupyter-book-gh:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build Jupyter Book
      run: jupyter-book build tests/docs 